[target.x86_64-unknown-none]
linker = "rust-lld"
rustflags = [
    "-Clink-arg=-Tplatform/__ARCH__/__BOARD__/linker.ld",
    "-Clink-arg=-no-pie",
    "-Clinker-flavor=ld.lld",
    "-Cforce-frame-pointers=yes",
    "-Ctarget-feature=-mmx,-sse,+soft-float",
    "-Cno-redzone=yes",
]