[target.aarch64-unknown-none]
rustflags = [
    "-Clink-arg=-Tplatform/__ARCH__/__BOARD__/linker.ld",
    "-Ctarget-feature=+a53,+v8a,+strict-align,-neon,-fp-armv8",
    "-Cforce-frame-pointers=yes",
]