#!/usr/bin/env bash
# Host-side helpers that consume repo-root .config (Kconfig + metadata from kconfig_cli.py).
# Usage (from repo root, or any cwd — script cds to root):
#   ./tools/kconfig/host_config.sh cargo   # write .cargo/config.toml
#   ./tools/kconfig/host_config.sh vscode # refresh .config + write .vscode/settings.json
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$ROOT"

KPY="$ROOT/tools/kconfig/.venv/bin/python"
CLI="$ROOT/tools/kconfig/kconfig_cli.py"

cmd_gen_cargo() {
	local CONFIG_TOML=".cargo/config.toml"
	echo "" >"$CONFIG_TOML"

	if [ ! -f .config ]; then
		echo "error: missing .config (run: make defconfig)" >&2
		exit 1
	fi
	local ARCH BOARD HVISOR_SRC LD_SCRIPT CONFIG_TOML_TEMPLATE
	ARCH=$(grep '^# ARCH=' .config 2>/dev/null | head -1 | sed 's/^# ARCH=//')
	[ -n "$ARCH" ] || ARCH=$(grep '^ARCH=' .config | head -1 | cut -d= -f2-)
	BOARD=$(grep '^# BOARD=' .config 2>/dev/null | head -1 | sed 's/^# BOARD=//')
	[ -n "$BOARD" ] || BOARD=$(grep '^BOARD=' .config | head -1 | cut -d= -f2-)
	HVISOR_SRC=$(grep '^# HVISOR_SRC=' .config 2>/dev/null | head -1 | sed 's/^# HVISOR_SRC=//')
	[ -n "$HVISOR_SRC" ] || HVISOR_SRC=$(grep '^HVISOR_SRC=' .config | head -1 | cut -d= -f2-)
	LD_SCRIPT=$(grep '^# LD_SCRIPT=' .config 2>/dev/null | head -1 | sed 's/^# LD_SCRIPT=//')
	[ -n "$LD_SCRIPT" ] || LD_SCRIPT=$(grep '^LD_SCRIPT=' .config | head -1 | cut -d= -f2-)
	CONFIG_TOML_TEMPLATE=$(grep '^# TEMPLATE=' .config 2>/dev/null | head -1 | sed 's/^# TEMPLATE=//')
	[ -n "$CONFIG_TOML_TEMPLATE" ] || CONFIG_TOML_TEMPLATE=$(grep '^TEMPLATE=' .config | head -1 | cut -d= -f2-)
	if [ -z "$ARCH" ] || [ -z "$BOARD" ] || [ -z "$HVISOR_SRC" ] || [ -z "$LD_SCRIPT" ] || [ -z "$CONFIG_TOML_TEMPLATE" ]; then
		echo "error: .config missing ARCH/BOARD/HVISOR_SRC/LD_SCRIPT/TEMPLATE lines (run: make defconfig)" >&2
		exit 1
	fi
	local TEMPLATE
	TEMPLATE=$(cat "$CONFIG_TOML_TEMPLATE")
	local HOST_ARCH OS OS_VERSION DISTRO
	HOST_ARCH=$(uname -m)
	OS=$(uname -s)
	OS_VERSION=$(uname -r)
	DISTRO=unknown
	if [ -f /etc/os-release ]; then
		DISTRO=$(grep '^ID=' /etc/os-release | cut -d= -f2)
	fi

	{
		echo "# Generated by tools/kconfig/host_config.sh cargo at $(date) ($(whoami)@$(hostname))"
		echo "# BASH_VERSION = $BASH_VERSION"
		echo "# HOST_ARCH    = $HOST_ARCH"
		echo "# OS_INFO      = $OS $OS_VERSION $DISTRO"
		echo "# ARCH         = $ARCH"
		echo "# BOARD        = $BOARD"
		echo "# (platform toggles come from .config CONFIG_* via build.rs)"
		echo "# HVISOR_SRC   = $HVISOR_SRC"
		echo "# LD_SCRIPT    = $LD_SCRIPT"
		echo "# TEMPLATE     = $CONFIG_TOML_TEMPLATE"
		echo ""
	} >>"$CONFIG_TOML"

	TEMPLATE=$(echo "$TEMPLATE" | sed -e 's/__ARCH__/'"$ARCH"'/g')
	TEMPLATE=$(echo "$TEMPLATE" | sed -e 's/__BOARD__/'"$BOARD"'/g')
	echo "$TEMPLATE" >>"$CONFIG_TOML"
}

cmd_vscode() {
	local ARCH="${ARCH:-}" BOARD="${BOARD:-}"
	if [ -n "${BID:-}" ]; then
		ARCH=$(echo "$BID" | cut -d'/' -f1)
		BOARD=$(echo "$BID" | cut -d'/' -f2)
	fi
	if [ -z "$ARCH" ] || [ -z "$BOARD" ]; then
		echo "ERROR: ARCH/BOARD not set, use BID=arch/board or ARCH=... BOARD=..." >&2
		exit 1
	fi
	if [ ! -x "$KPY" ]; then
		echo "ERROR: tools/kconfig/.venv missing. Run: ./tools/kconfig/bootstrap_venv.sh" >&2
		exit 1
	fi
	ARCH="$ARCH" BOARD="$BOARD" "$KPY" "$CLI" defconfig

	local CFG_JSON
	CFG_JSON=$("$KPY" "$CLI" vscode-cfgs .config kconfig/cfg_map.toml)

	local TARGET
	case "$ARCH" in
	aarch64) TARGET="aarch64-unknown-none" ;;
	riscv64) TARGET="riscv64gc-unknown-none-elf" ;;
	loongarch64) TARGET="loongarch64-unknown-none" ;;
	x86_64) TARGET="x86_64-unknown-none" ;;
	*)
		echo "ERROR: Unsupported ARCH value: $ARCH" >&2
		exit 1
		;;
	esac

	mkdir -p .vscode
	cat >.vscode/settings.json <<EOF
{
	"rust-analyzer.linkedProjects": [
		"./Cargo.toml"
	],
	"rust.target": "$TARGET",
	"rust.all_targets": false,
	"rust-analyzer.cargo.target": "$TARGET",
	"rust-analyzer.cargo.cfgs": $CFG_JSON
}
EOF
	echo "generated .vscode/settings.json for ARCH=$ARCH BOARD=$BOARD TARGET=$TARGET"
}

case "${1:-}" in
cargo) cmd_gen_cargo ;;
vscode) cmd_vscode ;;
*)
	echo "usage: $(basename "$0") cargo|vscode" >&2
	exit 2
	;;
esac
