#!/bin/bash

set -e

CONFIG_TOML=".cargo/config.toml"
echo "" > $CONFIG_TOML

function find_hvisor_src {
    # get the directory which contains CHANGELOG.md and "hvisor" in the file contents
    # this is the root of the hvisor source tree, return the absolute path
    ret=$(find . -name CHANGELOG.md -exec grep -q hvisor {} \; -print -quit)
    if [ -z "$ret" ]; then
        echo "Could not find hvisor source tree"
        exit 1
    fi
    echo $(dirname $ret)
}

CONFIG_TOML_TEMPLATE="platform/$ARCH/$BOARD/cargo/config.template.toml"
CONFIG_TOML_TEMPLATE=$(realpath $CONFIG_TOML_TEMPLATE)
TEMPLATE=$(cat $CONFIG_TOML_TEMPLATE)
LD_SCRIPT="platform/$ARCH/$BOARD/linker.ld"
LD_SCRIPT=$(realpath $LD_SCRIPT)
HVISOR_SRC=$(realpath $(find_hvisor_src))
HOST_ARCH=$(uname -m)
OS=$(uname -s)
OS_VERSION=$(uname -r)
DISTRO=unknown
if [ -f /etc/os-release ]; then
    DISTRO=$(grep '^ID=' /etc/os-release | cut -d= -f2)
fi

echo "# Generated by gen_cargo_config.sh at $(date) ($(whoami)@$(hostname))" >> $CONFIG_TOML
echo "# BASH_VERSION = $BASH_VERSION" >> $CONFIG_TOML
echo "# HOST_ARCH    = $HOST_ARCH" >> $CONFIG_TOML
echo "# OS_INFO      = $OS $OS_VERSION $DISTRO" >> $CONFIG_TOML
echo "# ARCH         = $ARCH" >> $CONFIG_TOML
echo "# BOARD        = $BOARD" >> $CONFIG_TOML
echo "# FEATURES     = $FEATURES" >> $CONFIG_TOML
echo "# HVISOR_SRC   = $HVISOR_SRC" >> $CONFIG_TOML
echo "# LD_SCRIPT    = $LD_SCRIPT" >> $CONFIG_TOML
echo "# TEMPLATE     = $CONFIG_TOML_TEMPLATE" >> $CONFIG_TOML
echo "" >> $CONFIG_TOML

# place holders: __XXX__ -> XXX
TEMPLATE=$(echo "$TEMPLATE" | sed -e 's/__ARCH__/'"$ARCH"'/g')
TEMPLATE=$(echo "$TEMPLATE" | sed -e 's/__BOARD__/'"$BOARD"'/g')

echo "$TEMPLATE" >> $CONFIG_TOML