#!/bin/bash

set -e

CONFIG_TOML=".cargo/config.toml"
echo "" > $CONFIG_TOML

function find_hvisor_src {
    # get the directory which contains CHANGELOG.md and "hvisor" in the file contents
    # this is the root of the hvisor source tree, return the absolute path
    ret=$(find . -name CHANGELOG.md -exec grep -q hvisor {} \; -print -quit)
    if [ -z "$ret" ]; then
        echo "Could not find hvisor source tree"
        exit 1
    fi
    echo $(dirname $ret)
}

RUSTFLAGS="platform/$ARCH/$BOARD/cargo/rustflags"
RUSTFLAGS=$(realpath $RUSTFLAGS)
rustflags=$(cat $RUSTFLAGS)
LD_SCRIPT="platform/$ARCH/$BOARD/linker.ld"
LD_SCRIPT=$(realpath $LD_SCRIPT)
HVISOR_SRC=$(realpath $(find_hvisor_src))
HOST_ARCH=$(uname -m)
OS=$(uname -s)
OS_VERSION=$(uname -r)
DISTRO=unknown
if [ -f /etc/os-release ]; then
    DISTRO=$(grep '^ID=' /etc/os-release | cut -d= -f2)
fi

echo "# Generated by gen_cargo_config.sh at $(date) ($(whoami)@$(hostname))" >> $CONFIG_TOML
echo "# BASH_VERSION = $BASH_VERSION" >> $CONFIG_TOML
echo "# HOST_ARCH    = $HOST_ARCH" >> $CONFIG_TOML
echo "# OS_INFO      = $OS $OS_VERSION $DISTRO" >> $CONFIG_TOML
echo "# ARCH         = $ARCH" >> $CONFIG_TOML
echo "# BOARD        = $BOARD" >> $CONFIG_TOML
echo "# FEATURES     = $FEATURES" >> $CONFIG_TOML
echo "# HVISOR_SRC   = $HVISOR_SRC" >> $CONFIG_TOML
echo "# LD_SCRIPT    = $LD_SCRIPT" >> $CONFIG_TOML
echo "# RUSTFLAGS    = $RUSTFLAGS" >> $CONFIG_TOML
echo "" >> $CONFIG_TOML
echo "[target.$RUSTC_TARGET]" >> $CONFIG_TOML
echo "runner = \"$HVISOR_SRC/tools/cargo_test.sh\"" >> $CONFIG_TOML
# for each line in rustflags file, append to $CONFIG_TOML
echo "rustflags = [" >> $CONFIG_TOML
echo "\"-Clink-arg=-T$LD_SCRIPT\"," >> $CONFIG_TOML
# iterate over each line in rustflags file
IFS=$'\n'
for line in $rustflags; do
    echo "adding $line"
    echo "\"$line\"," >> $CONFIG_TOML
done
echo "]" >> $CONFIG_TOML