#!/bin/bash

set -e

CONFIG_TOML=".cargo/config.toml"
echo "" > $CONFIG_TOML

RUSTFLAGS="platform/$ARCH/$BOARD/cargo/rustflags"
rustflags=$(cat $RUSTFLAGS)
LD_SCRIPT="platform/$ARCH/$BOARD/linker.ld"
HVISOR_SRC="$(pwd)"

echo "# Generated by gen_cargo_config.sh at $(date) on $(whoami)@$(hostname)" >> $CONFIG_TOML
echo "# BASH_VERSION = $BASH_VERSION" >> $CONFIG_TOML
echo "# ARCH         = $ARCH" >> $CONFIG_TOML
echo "# BOARD        = $BOARD" >> $CONFIG_TOML
echo "# LD_SCRIPT    = $LD_SCRIPT" >> $CONFIG_TOML
echo "# RUSTFLAGS    = $RUSTFLAGS" >> $CONFIG_TOML
echo "" >> $CONFIG_TOML
echo "[target.$RUSTC_TARGET]" >> $CONFIG_TOML
echo "runner = \"$HVISOR_SRC/tools/cargo_test.sh\"" >> $CONFIG_TOML
# for each line in rustflags file, append to $CONFIG_TOML
echo "rustflags = [" >> $CONFIG_TOML
echo "\"-Clink-arg=-T$LD_SCRIPT\"," >> $CONFIG_TOML
# iterate over each line in rustflags file
IFS=$'\n'
for line in $rustflags; do
    echo "adding $line"
    echo "\"$line\"," >> $CONFIG_TOML
done
echo "]" >> $CONFIG_TOML