# hvisor Github Actions CI
# wheatfox <wheatfox17@icloud.com>
#
# GitHub: format + license checks only. 

name: CI
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:
env:
  MODE: debug
jobs:
  linter:
    name: linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-none
          components: rust-src rustfmt
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-system-aarch64 qemu-system-riscv64 gdb-multiarch llvm-dev libclang-dev wget
          cargo install --version 0.3.0 --locked cargo-binutils
      - name: Format Check
        run: make fmt-test

  license-checker:
    name: license-checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: License Check
        run: |
          set -x
          ./tools/license_checker.sh
